### ISSUE TITLE
The app crashes when I call "mVpnController.connect"

### ISSUE THREAD

**Issue by aalsubhi** [UCI-Networking-Group/AntMonitor#1] opened 2019-11-03 14:35 UTC
Hello there,

I'm using AntMonitor library on HUAWEI Y7 Prime 2018 with Android 8.0.0. Whenever I try to use "mVpnController.connect" in my app, it crashes and got the following error message in the "Logcat"

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.antminitorlibtest, PID: 18714
    java.lang.RuntimeException: Unable to start service edu.uci.calit2.antmonitor.lib.vpn.VpnClient@c883462 with Intent { cmp=com.example.antminitorlibtest/edu.uci.calit2.antmonitor.lib.vpn.VpnClient }: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4179)
        at android.app.ActivityThread.-wrap21(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2119)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
        at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:860)
        at edu.uci.calit2.antmonitor.lib.vpn.VpnClient.buildVpnStateNotification(VpnClient.java:718)
        at edu.uci.calit2.antmonitor.lib.vpn.VpnClient.onStartCommand(VpnClient.java:211)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4151)

**Comment by nshuba** [comment] 2019-12-17 06:54
Hi aalsubhi,

Thanks for reporting. I tried reproducing, but with no success. Can I ask you to email me the source code of the project in which you are using AntMonitor? This will be the fastest way for me to debug.

**Comment by nshuba** [comment] 2019-12-19 06:40
I looked at your stack trace more closely today and I see that the process name responsible was the crash is "com.example.antminitorlibtest," however, the process name of our example app is "edu.uci.calit2.antexample." Perhaps when you were creating the project you accidentally missed some files from the example app?

The crash has to do with the icon, so I tried removing the bitmaps from the example app, but even in that case AntMonitor didn't crash - it fell back to its own icons... So I am not sure why you're experiencing this. Can I suggest you to start out with our example app as-is, without modifying anything and then going form there? If you're building your own version of AntMonitor, then you can also try commenting out line [718 in VpnClient](https://github.com/UCI-Networking-Group/AntMonitor/blob/master/antmonitorlib/src/main/java/edu/uci/calit2/antmonitor/lib/vpn/VpnClient.java#L718).

Hope that helps. I tested on Android 8.0.0 to match you. Closing this issue for now since I cannot reproduce.

**Closed as completed by nshuba** 2019-12-19 06:40 UTC
